<a href="https://colab.research.google.com/github/talhaDS04/pytorch-week4/blob/main/Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## OO. Pytorch fundamentals

Resource Notebook : https://www.learnpytorch.io/00_pytorch_fundamentals/

if you have a question : https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## introduction to tensor

###Creating Tensor


In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
M = torch.tensor([[7,8],
                  [9,10]])
M

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
M.ndim

2

In [ ]:
M[1]

tensor([ 9, 10])

In [ ]:
M.shape

torch.Size([2, 2])

In [ ]:
#TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
TENSOR[0][1]

tensor([3, 6, 9])

### Random Tensor

Torch random tensors -> "https://docs.pytorch.org/docs/stable/generated/torch.rand.html?utm_source=chatgpt.com"


In [ ]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6269, 0.2863, 0.3775, 0.2859],
        [0.8182, 0.1086, 0.6789, 0.7459],
        [0.8880, 0.0471, 0.3933, 0.8441]])

In [ ]:
# Create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(3,224,224) #height, width, color channel (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim



(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [ ]:
#create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors_like

In [ ]:
#use torch.range()
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.__version__

'2.6.0+cu124'

In [ ]:
one_to_ten =torch.arange(0,10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_six =torch.arange(start=0,end=100, step=17)
one_to_six

tensor([ 0, 17, 34, 51, 68, 85])

In [ ]:
#creating tensors like
six_zeros = torch.zeros_like(input=one_to_ten)
six_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [ ]:
#foat 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None) #what datatype is the tensor (e.g. float32 or float16)
                               #device=None,) #what device is your tensor on
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=torch.float16)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=torch.float32,
                               device=None, #what device is your tensor on
                               requires_grad=False) #whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

In [ ]:
#create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2195, 0.8927, 0.3237, 0.8470],
        [0.0903, 0.1367, 0.4508, 0.9519],
        [0.9319, 0.1591, 0.3086, 0.4459]])

In [ ]:
#find out some details about some tensors.
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.2195, 0.8927, 0.3237, 0.8470],
        [0.0903, 0.1367, 0.4508, 0.9519],
        [0.9319, 0.1591, 0.3086, 0.4459]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Maiuplating the tensors (tensors operations)

####Tensors operations include:
 1 Addition<br>
 2 Subtraction<br>
 3 Multiplication<br>
 4 Devision<br>
 5 Matrix Multiplication


In [ ]:
#create a tensor
tensor = torch.tensor([1,2,3])
tensor + 1000

tensor([1001, 1002, 1003])

In [ ]:
# Multiply by tensor by 10
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [ ]:
#subtract  10
tensor - 10


tensor([ 0, 10, 20])

In [ ]:
# Try out pytorch in-build functions
torch.mul(tensor,10)

tensor([100, 200, 300])

In [ ]:
tensor

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([20, 30, 40])

### Matrix Multiplication

Two main ways of performing multiplication in neural network or deep learning:

1. Element-wise multiplication
2. MATRIX multiplication (dot product)

In [ ]:
#Element-wise multiplication.
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals: tensor([100, 400, 900])


In [ ]:
#Matrix multiplication
torch.matmul(tensor,tensor)

tensor(1400)

In [ ]:
%time
value=0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 5.72 µs
tensor(1400)


In [ ]:
%time
torch.matmul(tensor,tensor)

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 5.96 µs


tensor(1400)

In [ ]:
tensor @ tensor

tensor(1400)

### one of the most common errors in deep learning: Shape errors

In [ ]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensors multiplication issue, we use **transpose**.

A **transpose** switches the axes or dimensions of given tensor

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
torch.mm(tensor_A,tensor_B.T) #mm is the alias version of matmul

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
torch.mm(tensor_A,tensor_B.T).shape

torch.Size([3, 3])

##Finding the min, max ,mean,sum ,etc(tensor aggregation)

In [ ]:
#create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#find the min
torch.min(x)

tensor(0)

In [ ]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
#find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
#find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean() #torch.mean function requires a tensor of float32 datatype to work.

(tensor(45.), tensor(45.))

In [ ]:
#find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

##Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#finding the position of minimum argument
x.argmin()

tensor(0)

In [ ]:
#finding the position of maximum argument
x.argmax()

tensor(9)

##Reshaping, Stacking , squeezing , Unsqueezing tensors


1. Reshaping - reshape an input tensor to define shape
2. View - Return a view of input tensor of certain shape but keep the same memory as the original tensor
3. Stacking -  Combine multiple tensorson top of each other (vertical stack/vstack) or side by side (horizontel stack/hstack)
4. squeez - removes "1" dimensions from a tensor
5. Unsqueez - add a "1" dimension to a tensor
6. Permute - Return a view of the input with dimension permuted(swapped) in a certain way.

In [ ]:
#let's create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#change the view (view of a tensor share the original memory of a tensor)
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#changing z changes x
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
x

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
#stack tensors on top of eachother
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeez - removes all single dimensions from target tensor
x_reshaped, x_reshaped.shape



(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_reshaped = x_reshaped.squeeze() #remove extra dimension from tenor
print(f"new tensor: {x_reshaped}")
print(f"new tensor shape: {x_reshaped.shape}")


new tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
new tensor shape: torch.Size([9])


In [ ]:
# tensor.unsqueez- add one dimension to a target tensor at a specific dim(dimension)
print(f"previous tensor: {x_reshaped}")
print(f"previous tensor shape: {x_reshaped.shape}")

previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous tensor shape: torch.Size([9])


In [ ]:
#Add an extra dimension with unsqueez
x_unsqueezed = x_reshaped.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
#torch.permute - rearange the dimension of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) #[height, width, color_channels]

#permute the original tensor to rearange the axis(or dim).
x_permuted = x_original.permute(2,0,1) #shift axis 0->1, 1->2, 2->0

print(f"previous shape: {x_original.shape}")
print(f"new shape: {x_permuted.shape}")

previous shape: torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0,0,0] = 72
x_original[0,0,0] , x_permuted[0,0,0]


(tensor(72.), tensor(72.))

## Indexing (selecting data from tensors)


Indexing of tensors is similar tha indexing of numpy

In [ ]:
# create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#let's index on middle bracket (dim=1)
x[0][0], x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
#let's index on most inner bracket
x[0][0][0], x[0,0,0]

(tensor(1), tensor(1))

In [ ]:
#Get 0 of 0th and 1st dimension and all dimension of 2nd dimension.
x[0,0,:]

tensor([1, 2, 3])

##Pytorch tensors and numpy

Numpy is the popular scientific python numerical computing library.
And bcz of this , Pytorch has functionality to react with it.
1. Data in Numpy, want in PyTorch tensor -> torch.from_numpy(ndarray)
2. From pyTorch to Numpy -> torch.Tensor.numpy()

In [ ]:
#Numpy array to PyTorch Tensor
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32) #Converting float64 to float32 bcz when we change array to tensor give default float64
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float32)

In [ ]:
#change the value of array
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
#Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

##Reproducbility(trying to take random out of random)


In [ ]:
import torch

#create two random tensor
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)

tensor([[0.8901, 0.2221, 0.9433, 0.2223],
        [0.2336, 0.9305, 0.8696, 0.9090],
        [0.8113, 0.1968, 0.5691, 0.4611]])
tensor([[0.2174, 0.6245, 0.0747, 0.3101],
        [0.9003, 0.1086, 0.8526, 0.7793],
        [0.1373, 0.8217, 0.6965, 0.3240]])


In [ ]:
print(random_tensor_A == random_tensor_B)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#let's make random but reproducibile tensors
import torch

#set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


##Running Tensors and pyTorch objects on GPUs(and making faster computations).

In [ ]:
!nvidia-smi

Wed Jul  9 04:23:41 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   51C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

###Check for GPU access with PyTorch.

In [ ]:
#check for GPU to access with pyTorch
import torch
torch.cuda.is_available()

True

In [ ]:
#setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#Count number of devices
torch.cuda.device_count()

1